name: birthday_beacon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_notifications: any
  awesome_notifications_core: ^0.9.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.1
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  sqflite: ^2.3.3+1
  timezone: ^0.9.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
